In [1]:
import tensorflow as tf

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]


# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]


X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 3])

W = tf.Variable(tf.random_normal([3, 3]), name='weight')
b = tf.Variable(tf.random_normal([3]), name='bias')

# hypothesis - softmax
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
# cost
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=-1))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train = optimizer.minimize(cost)

# accuracy
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, train], feed_dict={X:x_data, Y:y_data})
        print(step, cost_val, W_val)
    print(sess.run(prediction, feed_dict={X:x_test}))
    print(sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))


0 7.39412 [[ 2.66075969 -1.91228414  1.89890826]
 [ 0.93519604 -0.09392278 -0.34074536]
 [ 0.08938822  0.3074688   0.59253603]]
1 4.88733 [[ 2.58654881 -1.87500989  1.93584502]
 [ 0.66201508  0.08053626 -0.24202345]
 [-0.18231302  0.4941285   0.67757756]]
2 2.52179 [[ 2.5230844  -1.84290087  1.96720028]
 [ 0.42581326  0.23502594 -0.16031131]
 [-0.40139532  0.65520614  0.73558223]]
3 1.76031 [[ 2.51347351 -1.85397613  1.98788643]
 [ 0.4690533   0.15660596 -0.12513138]
 [-0.3365674   0.58400321  0.74195725]]
4 1.69414 [[ 2.49008107 -1.84369254  2.0009954 ]
 [ 0.43769184  0.1925578  -0.12972175]
 [-0.34144521  0.62614244  0.70469582]]
5 1.66178 [[ 2.47350407 -1.84513378  2.01901364]
 [ 0.44367298  0.1658989  -0.109044  ]
 [-0.31187767  0.6052838   0.69598693]]
6 1.63737 [[ 2.45273161 -1.83984554  2.03449798]
 [ 0.42656705  0.1758002  -0.10183937]
 [-0.30432567  0.62071007  0.67300868]]
7 1.61549 [[ 2.43464613 -1.83866537  2.05140328]
 [ 0.42386979  0.16409776 -0.08743969]
 [-0.28365123  0

# Learning rate: Nan!

- too big - Overshooting 
- too small - Many iterations and local minimum

In [2]:
# Too big learning rate
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=10)
train = optimizer.minimize(cost)

# accuracy
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, train], feed_dict={X:x_data, Y:y_data})
        print(step, cost_val, W_val)
    print(sess.run(prediction, feed_dict={X:x_test}))
    print(sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))


0 10.0897 [[  1.4659946    4.16874695  -6.56966543]
 [ 16.0956459   16.48018074 -31.9899044 ]
 [ 15.84082985  18.14456177 -34.57529831]]
1 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
2 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
3 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
4 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
5 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
6 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
7 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
8 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
9 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
10 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
11 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
12 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
13 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
14 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
15 n

In [3]:
# too small learning rate
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10)
train = optimizer.minimize(cost)

# accuracy
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, train], feed_dict={X:x_data, Y:y_data})
        print(step, cost_val, W_val)
    print(sess.run(prediction, feed_dict={X:x_test}))
    print(sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))

0 7.57058 [[-1.46288693  0.03284102  0.82841444]
 [-0.2362438   3.40156984 -0.23638186]
 [-0.08033941 -1.06420612 -0.10165976]]
1 7.57058 [[-1.46288693  0.03284102  0.82841444]
 [-0.2362438   3.40156984 -0.23638186]
 [-0.08033941 -1.06420612 -0.10165976]]
2 7.57058 [[-1.46288693  0.03284102  0.82841444]
 [-0.2362438   3.40156984 -0.23638186]
 [-0.08033941 -1.06420612 -0.10165976]]
3 7.57058 [[-1.46288693  0.03284102  0.82841444]
 [-0.2362438   3.40156984 -0.23638186]
 [-0.08033941 -1.06420612 -0.10165976]]
4 7.57058 [[-1.46288693  0.03284102  0.82841444]
 [-0.2362438   3.40156984 -0.23638186]
 [-0.08033941 -1.06420612 -0.10165976]]
5 7.57058 [[-1.46288693  0.03284102  0.82841444]
 [-0.2362438   3.40156984 -0.23638186]
 [-0.08033941 -1.06420612 -0.10165976]]
6 7.57058 [[-1.46288693  0.03284102  0.82841444]
 [-0.2362438   3.40156984 -0.23638186]
 [-0.08033941 -1.06420612 -0.10165976]]
7 7.57058 [[-1.46288693  0.03284102  0.82841444]
 [-0.2362438   3.40156984 -0.23638186]
 [-0.08033941 -1

# Non-normalized input

In [15]:
import numpy as np
from sklearn import preprocessing
import tensorflow as tf
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
# min-max scaler : 0과 1사이로 정규화
min_max_scaler = preprocessing.MinMaxScaler()
xy = min_max_scaler.fit_transform(xy)
print(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# hypothesis - softmax
hypothesis = tf.matmul(X, W) + b
# cost
cost = tf.reduce_mean(tf.square(hypothesis-Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# accuracy
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, train], feed_dict={X:x_data, Y:y_data})
        print(step, cost_val, W_val)

    

[[ 1.          1.          0.          1.          1.        ]
 [ 0.70548491  0.70439552  1.          0.71881783  0.83755792]
 [ 0.54412549  0.50274824  0.57608696  0.60646801  0.6606331 ]
 [ 0.33890353  0.31368023  0.10869565  0.45989134  0.43800918]
 [ 0.51436     0.4258239   0.30434783  0.58504805  0.42624401]
 [ 0.49556179  0.4258239   0.31521739  0.48131134  0.49276137]
 [ 0.11436064  0.          0.20652174  0.22007776  0.18597238]
 [ 0.          0.07747099  0.5326087   0.          0.        ]]
0 8.21743 [[-0.04905197]
 [-1.61256278]
 [-0.71570534]
 [ 0.14097178]]
1 8.21681 [[-0.04902199]
 [-1.6125344 ]
 [-0.71568292]
 [ 0.14100388]]
2 8.21618 [[-0.04899201]
 [-1.61250603]
 [-0.71566051]
 [ 0.14103597]]
3 8.21555 [[-0.04896203]
 [-1.61247766]
 [-0.7156381 ]
 [ 0.14106807]]
4 8.21492 [[-0.04893205]
 [-1.61244929]
 [-0.71561569]
 [ 0.14110017]]
5 8.2143 [[-0.04890208]
 [-1.61242092]
 [-0.71559328]
 [ 0.14113227]]
6 8.21367 [[-0.0488721 ]
 [-1.61239254]
 [-0.71557087]
 [ 0.14116436]]