In [10]:
import tensorflow as tf

x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

nb_classes = 3

X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, nb_classes])

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis)))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train = optimizer.minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        sess.run(train, feed_dict={X: x_data, Y:y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}))
    a = sess.run(hypothesis, feed_dict={X:[[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(a, sess.run(tf.arg_max(a, 1)))

0 45.5599
200 46.9457
400 52.3988
600 17.8503
800 43.1657
1000 0.0333361
1200 0.018568
1400 0.0136536
1600 0.0111608
1800 0.00969609
2000 0.0087942
[[  1.37629708e-12   1.00000000e+00   3.85012999e-14]
 [  9.99949217e-01   5.07220466e-05   1.64425007e-08]
 [  1.15808901e-36   2.69546314e-14   1.00000000e+00]] [1 0 2]
