# Learning rate: Nan!
- too big - Overshooting 
- too small - Many iterations and local minimum

# Preprocessing for Gradient Descent Algorithm
- normalized data

# Overfitting
- more training data
- Regularization(일반화)
cost = cost' + l2reg 
(regularzation strength : 0-고려하지 않는다. 1- 중요하다)    
l2reg = 0.001 * tf.reduce_sum(tf.square(W))

# Training and Test datasets

In [2]:
import tensorflow as tf

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]


# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]


X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 3])

W = tf.Variable(tf.random_normal([3, 3]), name='weight')
b = tf.Variable(tf.random_normal([3]), name='bias')

# hypothesis - softmax
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
# cost
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=-1))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train = optimizer.minimize(cost)

# accuracy
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, train], feed_dict={X:x_data, Y:y_data})
        print(step, cost_val, W_val)
    print(sess.run(prediction, feed_dict={X:x_test}))
    print(sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))


0 5.43529 [[-2.3960669   1.03212094  1.34361959]
 [-1.58879983  0.62896901  0.85064673]
 [ 2.09485173 -1.92407072 -1.14652336]]
1 3.67316 [[-2.42423582  1.06784725  1.33606207]
 [-1.66432559  0.79977822  0.75536329]
 [ 1.97116554 -1.73900402 -1.20790386]]
2 2.67986 [[-2.4499321   1.10018241  1.32942307]
 [-1.72657645  0.95932043  0.65807194]
 [ 1.86099839 -1.56178534 -1.27495539]]
3 1.90257 [[-2.47152328  1.11734629  1.33385038]
 [-1.76648295  1.04260838  0.61469054]
 [ 1.77357996 -1.44553447 -1.30378783]]
4 1.7291 [[-2.48085046  1.11252201  1.34800196]
 [-1.73564124  1.00431669  0.62214047]
 [ 1.7581681  -1.43976116 -1.29414916]]
5 1.70115 [[-2.49169254  1.11238205  1.35898399]
 [-1.71421659  0.991211    0.61382157]
 [ 1.73333335 -1.41118753 -1.29788804]]
6 1.67603 [[-2.50158119  1.11050749  1.37074721]
 [-1.68754244  0.96816581  0.61019254]
 [ 1.71396112 -1.39216793 -1.29753542]]
7 1.65155 [[-2.51176047  1.10947692  1.38195717]
 [-1.66292644  0.94942784  0.60431451]
 [ 1.69261479 -1.

 [ 0.4279449  -0.27729014 -1.12639618]]
110 0.566171 [[-3.19970703  1.03148985  2.14789104]
 [-0.0677311  -0.08026022  0.03880738]
 [ 0.42558318 -0.27598035 -1.12534428]]
111 0.564969 [[-3.20343375  1.03002906  2.15307856]
 [-0.06398112 -0.08081234  0.03560951]
 [ 0.42331097 -0.27472192 -1.12433052]]
112 0.563793 [[-3.2071383   1.02857327  2.15823889]
 [-0.06032771 -0.08131478  0.03245854]
 [ 0.4211255  -0.27351236 -1.12335455]]
113 0.562643 [[-3.21082139  1.02712286  2.16337228]
 [-0.05676779 -0.08177005  0.0293539 ]
 [ 0.41902408 -0.27234939 -1.12241614]]
114 0.561517 [[-3.2144835   1.02567804  2.1684792 ]
 [-0.05329837 -0.08218065  0.02629509]
 [ 0.41700423 -0.27123085 -1.1215148 ]]
115 0.560413 [[-3.21812534  1.02423918  2.1735599 ]
 [-0.04991664 -0.08254883  0.02328156]
 [ 0.41506338 -0.2701546  -1.12065017]]
116 0.559333 [[-3.2217474   1.02280664  2.17861462]
 [-0.04661981 -0.08287688  0.02031276]
 [ 0.41319919 -0.26911873 -1.11982191]]
117 0.558273 [[-3.22535038  1.02138066  2.1

# Learning rate: Nan!

- too big - Overshooting 
- too small - Many iterations and local minimum

In [3]:
# Too big learning rate
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=10)
train = optimizer.minimize(cost)

# accuracy
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, train], feed_dict={X:x_data, Y:y_data})
        print(step, cost_val, W_val)
    print(sess.run(prediction, feed_dict={X:x_test}))
    print(sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))


0 4.34113 [[  2.42704201   5.92995501  -4.94189882]
 [ 16.03811646  16.74927711 -32.04725647]
 [ 14.58864975  18.18997383 -33.19539642]]
1 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
2 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
3 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
4 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
5 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
6 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
7 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
8 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
9 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
10 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
11 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
12 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
13 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
14 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
15 n

169 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
170 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
171 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
172 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
173 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
174 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
175 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
176 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
177 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
178 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
179 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
180 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
181 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
182 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
183 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
184 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan

In [3]:
# too small learning rate
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10)
train = optimizer.minimize(cost)

# accuracy
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, train], feed_dict={X:x_data, Y:y_data})
        print(step, cost_val, W_val)
    print(sess.run(prediction, feed_dict={X:x_test}))
    print(sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))

0 7.57058 [[-1.46288693  0.03284102  0.82841444]
 [-0.2362438   3.40156984 -0.23638186]
 [-0.08033941 -1.06420612 -0.10165976]]
1 7.57058 [[-1.46288693  0.03284102  0.82841444]
 [-0.2362438   3.40156984 -0.23638186]
 [-0.08033941 -1.06420612 -0.10165976]]
2 7.57058 [[-1.46288693  0.03284102  0.82841444]
 [-0.2362438   3.40156984 -0.23638186]
 [-0.08033941 -1.06420612 -0.10165976]]
3 7.57058 [[-1.46288693  0.03284102  0.82841444]
 [-0.2362438   3.40156984 -0.23638186]
 [-0.08033941 -1.06420612 -0.10165976]]
4 7.57058 [[-1.46288693  0.03284102  0.82841444]
 [-0.2362438   3.40156984 -0.23638186]
 [-0.08033941 -1.06420612 -0.10165976]]
5 7.57058 [[-1.46288693  0.03284102  0.82841444]
 [-0.2362438   3.40156984 -0.23638186]
 [-0.08033941 -1.06420612 -0.10165976]]
6 7.57058 [[-1.46288693  0.03284102  0.82841444]
 [-0.2362438   3.40156984 -0.23638186]
 [-0.08033941 -1.06420612 -0.10165976]]
7 7.57058 [[-1.46288693  0.03284102  0.82841444]
 [-0.2362438   3.40156984 -0.23638186]
 [-0.08033941 -1

# Non-normalized input

In [15]:
import numpy as np
from sklearn import preprocessing
import tensorflow as tf
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
# min-max scaler : 0과 1사이로 정규화
min_max_scaler = preprocessing.MinMaxScaler()
xy = min_max_scaler.fit_transform(xy)
print(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# hypothesis - softmax
hypothesis = tf.matmul(X, W) + b
# cost
cost = tf.reduce_mean(tf.square(hypothesis-Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# accuracy
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, train], feed_dict={X:x_data, Y:y_data})
        print(step, cost_val, W_val)

    

[[ 1.          1.          0.          1.          1.        ]
 [ 0.70548491  0.70439552  1.          0.71881783  0.83755792]
 [ 0.54412549  0.50274824  0.57608696  0.60646801  0.6606331 ]
 [ 0.33890353  0.31368023  0.10869565  0.45989134  0.43800918]
 [ 0.51436     0.4258239   0.30434783  0.58504805  0.42624401]
 [ 0.49556179  0.4258239   0.31521739  0.48131134  0.49276137]
 [ 0.11436064  0.          0.20652174  0.22007776  0.18597238]
 [ 0.          0.07747099  0.5326087   0.          0.        ]]
0 8.21743 [[-0.04905197]
 [-1.61256278]
 [-0.71570534]
 [ 0.14097178]]
1 8.21681 [[-0.04902199]
 [-1.6125344 ]
 [-0.71568292]
 [ 0.14100388]]
2 8.21618 [[-0.04899201]
 [-1.61250603]
 [-0.71566051]
 [ 0.14103597]]
3 8.21555 [[-0.04896203]
 [-1.61247766]
 [-0.7156381 ]
 [ 0.14106807]]
4 8.21492 [[-0.04893205]
 [-1.61244929]
 [-0.71561569]
 [ 0.14110017]]
5 8.2143 [[-0.04890208]
 [-1.61242092]
 [-0.71559328]
 [ 0.14113227]]
6 8.21367 [[-0.0488721 ]
 [-1.61239254]
 [-0.71557087]
 [ 0.14116436]]