# RNN in TensorFlow
![rnn_character_level_language_model](./images/rnn_character_level_language_model.png)
1. cell을 만든다.
    ````py
    cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    ````
    
2. cell을 구동시킨다.
    ````py
    outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    ````

In [1]:
import tensorflow as tf
import numpy as np
import pprint

pp = pprint.PrettyPrinter(indent=4)

hidden_size = 2
cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size)

x_data = np.array([[[1, 0, 0, 0]]], dtype=np.float32)
outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[-0.08434204, -0.09535209]]], dtype=float32)


# Unfolding to n sequences
![unfolding_to_n_sequences](./images/unfolding_to_n_sequences.png)

In [4]:
import tensorflow as tf
import numpy as np
import pprint

pp = pprint.PrettyPrinter(indent=4)
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

hidden_size = 2
cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size, reuse=True)
x_data = np.array([[h, e, l, l, o]], dtype=np.float32)
print(x_data.shape)
pp.pprint(x_data)

outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

(1, 5, 4)
array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]]], dtype=float32)
array([[[ 0.02388728,  0.156087  ],
        [-0.01632774,  0.00951542],
        [ 0.07913802, -0.12146723],
        [ 0.14599977, -0.20274387],
        [ 0.17822623, -0.12653799]]], dtype=float32)


# Batch input
- input shape : [ x, y, z ]
    - x: batch_size
    - y: sequence_lengt h
    - z: input_data의 수
- output shape : [x, y, a ]
    - x, y: input과 동일
    - a: hidden_size(사용자가 임의

In [5]:
import tensorflow as tf
import numpy as np
import pprint

pp = pprint.PrettyPrinter(indent=4)
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

hidden_size = 2
x_data = np.array([[h, e, l, l, o], [e, o, l, l, l], [l, l, e, e, l]], dtype=np.float32)
print(x_data.shape)
pp.pprint(x_data)

cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True, reuse=True)
outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

(3, 5, 4)
array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]],

       [[ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.]],

       [[ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]]], dtype=float32)
array([[[ 0.12979445,  0.07883614],
        [ 0.28658816, -0.05230466],
        [ 0.31287771, -0.11677535],
        [ 0.34744418, -0.13164021],
        [ 0.16676456, -0.00182998]],

       [[ 0.16022775, -0.09281054],
        [ 0.01609805, -0.04037464],
        [ 0.10739429, -0.12299003],
        [ 0.18587042, -0.15650012],
        [ 0.24797827, -0.16885191]],

       [[ 0.09427112, -0.09002609],
        [ 0.17533794, -0.13783869],
        [ 0.28169456, -0.13047373],
        [ 0.33344358, -0.14673674],
        [ 0