In [7]:
import tensorflow as tf

x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

nb_classes = 3

X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, nb_classes])

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis)))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train = optimizer.minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        sess.run(train, feed_dict={X: x_data, Y:y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}))
    a = sess.run(hypothesis, feed_dict={X:[[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(a, sess.run(tf.arg_max(a, 1)))

0 101.883
200 13.922
400 66.1743
600 20.9159
800 15.814
1000 0.0343882
1200 0.0192381
1400 0.014194
1600 0.0116216
1800 0.0100886
2000 0.00911343
[[  3.97828732e-12   1.00000000e+00   2.50967002e-14]
 [  9.99891877e-01   1.08153472e-04   3.62849093e-08]
 [  8.84327489e-37   6.37307318e-14   1.00000000e+00]] [1 0 2]


0 [array([[  7.61933148e-01,   2.28486672e-01,   9.58013814e-03],
       [  5.37608147e-01,   4.50841546e-01,   1.15502803e-02],
       [  1.78678453e-01,   8.19993973e-01,   1.32758974e-03],
       [  1.62100509e-01,   8.37536216e-01,   3.63236031e-04],
       [  9.96921837e-01,   3.07813985e-03,   1.66563874e-09],
       [  6.70093954e-01,   3.29903960e-01,   2.07394942e-06],
       [  9.92439508e-01,   7.56052183e-03,   1.56792057e-09],
       [  9.96962726e-01,   3.03725316e-03,   4.63959218e-11]], dtype=float32), 22.813805]
200 [array([[  1.51410440e-08,   2.39373385e-05,   9.99976039e-01],
       [  2.46582044e-08,   5.75542212e-01,   4.24457759e-01],
       [  1.57652260e-18,   9.98711467e-01,   1.28852669e-03],
       [  4.25382638e-21,   9.99999404e-01,   6.32561353e-07],
       [  6.88219130e-01,   3.11719179e-01,   6.16568504e-05],
       [  9.58020035e-12,   1.00000000e+00,   4.69770402e-14],
       [  4.25079092e-03,   9.95749235e-01,   9.22743604e-10],
       [  1.2896545