# Multivariable Linear regression

H(x1, x2, x3) = x1w1 + x2w2 + x3w3
=> 영향을 주는 x값이 많을 수록 정확도가 올라간다.

In [5]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

# hypothesis
hypothesis = x1*w1 + x2*w2 + x3*w3 + b

# cost
cost = tf.reduce_mean(tf.square(hypothesis-Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step%10==0:
        print(step, "cost: ", cost_val, "hypothesis: ", hy_val)

0 cost:  90937.6 hypothesis:  [-116.31463623 -136.99963379 -136.37928772 -147.21260071 -105.22640228]
10 cost:  2.45675 hypothesis:  [ 150.44494629  183.62893677  179.5397644   196.81497192  139.33358765]
20 cost:  1.62224 hypothesis:  [ 151.2502594   184.60032654  180.49513245  197.85502625  140.07566833]
30 cost:  1.62021 hypothesis:  [ 151.25091553  184.60455322  180.49754333  197.85731506  140.08000183]
40 cost:  1.61819 hypothesis:  [ 151.24913025  184.60585022  180.49707031  197.85647583  140.08213806]
50 cost:  1.61619 hypothesis:  [ 151.24734497  184.60713196  180.49659729  197.8556366   140.08424377]
60 cost:  1.61418 hypothesis:  [ 151.24555969  184.60839844  180.49609375  197.85476685  140.08633423]
70 cost:  1.61218 hypothesis:  [ 151.24377441  184.60968018  180.49562073  197.85391235  140.08843994]
80 cost:  1.61021 hypothesis:  [ 151.24200439  184.6109314   180.49514771  197.85305786  140.09051514]
90 cost:  1.60824 hypothesis:  [ 151.24023438  184.61219788  180.49465942 

# Matrix

In [8]:
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [158.], [180.], [196.], [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3])# n개의 instance : None, 변수의 개수 3
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')
# hypothesis
hypothesis = tf.matmul(X, W) + b

# cost
cost = tf.reduce_mean(tf.square(hypothesis-Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step%10==0:
        print(step, "cost: ", cost_val, "hypothesis: ", hy_val)
        print(sess.run(W), sess.run(b))

0 cost:  57744.7 hypothesis:  [[-58.54107666]
 [-83.06881714]
 [-75.0114212 ]
 [-84.5005722 ]
 [-64.32535553]]
[[-0.07327712]
 [ 1.25116909]
 [-0.78525871]] [-0.60906225]
10 cost:  79.0802 hypothesis:  [[ 153.88900757]
 [ 172.25572205]
 [ 176.56459045]
 [ 189.45849609]
 [ 130.42356873]]
[[ 0.44672352]
 [ 1.77054322]
 [-0.25971383]] [-0.60294527]
20 cost:  78.5509 hypothesis:  [[ 154.53210449]
 [ 173.02809143]
 [ 177.32597351]
 [ 190.28674316]
 [ 131.01330566]]
[[ 0.44850013]
 [ 1.77220964]
 [-0.25841931]] [-0.60285497]
30 cost:  78.5495 hypothesis:  [[ 154.53439331]
 [ 173.0302887 ]
 [ 177.32849121]
 [ 190.28858948]
 [ 131.01557922]]
[[ 0.44870868]
 [ 1.77230978]
 [-0.25871098]] [-0.60278285]
40 cost:  78.5479 hypothesis:  [[ 154.53474426]
 [ 173.03012085]
 [ 177.32867432]
 [ 190.28793335]
 [ 131.01608276]]
[[ 0.44891256]
 [ 1.77240515]
 [-0.2590073 ]] [-0.60271072]
50 cost:  78.5466 hypothesis:  [[ 154.53507996]
 [ 173.02998352]
 [ 177.32888794]
 [ 190.28727722]
 [ 131.01657104]]
[[ 0