In [5]:
import numpy as np
import tensorflow as tf
import pprint
tf.set_random_seed(777)

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [6]:
# 1차원
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1]) # -1의 의미 : 마지막
print(t[:2], t[3:])

1
(7,)
0.0 1.0 6.0
[ 2.  3.  4.] [ 4.  5.]
[ 0.  1.] [ 3.  4.  5.  6.]


In [8]:
# 2차원
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim)  # rank
print(t.shape) # shape

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


In [12]:
# Shape, Rank, Axis
t = tf.constant([1, 2, 3, 4]) 
tf.shape(t).eval()

array([4])

In [11]:
t = tf.constant([[1, 2], 
                 [3, 4]])
tf.shape(t).eval()

array([2, 2])

In [15]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], 
                  [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

In [22]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.], [2.]])

print("Matrix 1 shape", matrix1.shape)
print("Matrix 2 shape", matrix2.shape)
tf.matmul(matrix1, matrix2).eval()
(matrix1*matrix2).eval() # broadcasting

Matrix 1 shape (2, 2)
Matrix 2 shape (2, 1)


array([[  5.],
       [ 11.]], dtype=float32)

In [24]:
# reduce_mean : 평균
tf.reduce_mean([1.0, 2.0], axis=0).eval()

1.5

In [25]:
x = [[1., 2.], [3., 4.]]
tf.reduce_mean(x).eval()

2.5

In [26]:
tf.reduce_mean(x, axis=0).eval()

array([ 2.,  3.], dtype=float32)

In [27]:
tf.reduce_mean(x, axis=1).eval()

array([ 1.5,  3.5], dtype=float32)

In [28]:
tf.reduce_mean(x, axis=-1).eval()

array([ 1.5,  3.5], dtype=float32)

In [29]:
# reduce_sum : 모든 원소를 더함
x = [[1., 2.], [3., 4.]]
tf.reduce_sum(x).eval()

10.0

In [30]:
tf.reduce_sum(x, axis=0).eval()

array([ 4.,  6.], dtype=float32)

In [31]:
tf.reduce_sum(x, axis=1).eval()

array([ 3.,  7.], dtype=float32)

In [32]:
tf.reduce_sum(x, axis=-1).eval()

array([ 3.,  7.], dtype=float32)

In [33]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

In [34]:
# Argmax : 최대값의 위치
x = [[0, 1, 2], [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0], dtype=int64)

In [35]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

In [36]:
tf.argmax(x, axis=-1).eval()

array([2, 0], dtype=int64)

In [37]:
# Reshape
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
t.shape

(2, 2, 3)

In [38]:
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
tf.reshape(t, shape=[-1, 1, 3])